NAME=testOutput0
ifeq ($(NO_OPT),)
	NO_OPT=1
endif
ifeq ($(NO_INLINE),)
	NO_INLINE=1
endif
LEVEL = ../../..
include $(LEVEL)/Makefile.common
cc     testOutput0.c   -o testOutput0
checksum = 250666804
